python3 main.py \
--model xception \
--device cuda \
--epoch 100 \
--random_state 42 \
--batch_size 32 \
--data_dir /Data/data \
--save_dir /Data/result/custom/xception01 \
--train_size 0.7 \
--learning_rate 0.001 \
