python3 main.py \
--xception_type A \
--device cuda \
--epoch 1000 \
--random_state 42 \
--batch_size 64 \
--data_dir /workspace/data \
--save_dir /workspace/result/typeA/try01 \
--train_size 0.7 \
--learning_rate 0.01 \
